// <auto-generated />
namespace PetCare_CasoEstudio2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CE02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CE02));
        
        string IMigrationMetadata.Id
        {
            get { return "202504191932217_CE02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
